parameters:
  - name: artifactBuildID
    displayName: Model CI Build ID
    type: string
    default: latest

pr: none
trigger: none

resources:
  containers:
    - container: mlops
      image: andysong199086/mlops-image:2.0
  pipelines:
    - pipeline: model-train-ci
      source: Model-Train-Register-CI
      trigger:
        branches:
          include:
            - main  

variables:
  - group: devopsforai-aml-vg
  - template: diabetes_variables_template.yml

stages:
  - stage: Deploy_ACI
    displayName: Deploy to ACI
    condition: variables['ACI_DEPLOYMENT_NAME']
    jobs:
      - job: ACI_Deployment
        displayName: ACI Deployment
        container: mlops
        timeoutInMinutes: 0
        steps: 
          - download: none
          - template: diabetes_get_model_artifacts.yml
            parameters:
              projectID: '$(resources.pipeline.model-train-ci.projectID)'
              pipelineID: '$(resources.pipeline.model-train-ci.pipelineID)'
              artifactBuildID: ${{ parameters.artifactBuildID }}
          - task: AzureCLI@1
            displayName: Install Azure CLI
            inputs:
              azureSubscription: $(WORKSPACE_SVC_CONNECTION)
              scriptLocation: inlineScript
              workingDirectory: $(Build.SourcesDirectory)
              inlineScript: az extension add -n azure-cli-ml
          - task: AzureCLI@1
            displayName: 'Deploy to ACI'
            inputs:
              azureSubscription: $(WORKSPACE_SVC_CONNECTION)
              scriptLocation: inlineScript
              workingDirectory: $(Build.SourcesDirectory)/$(SOURCE_TRAIN_DIRECTORY)/scoring
              inlineScript: |
                set -e
                az ml model deploy --name $(ACI_DEPLOYMENT_NAME) --model '$(get_model.MODEL_NAME):$(get_model.MODEL_VERSION)' \
                --ic inference_config.yml \
                --dc deployment_config_aci.yml \
                -g $(RESOURCE_GROUP) --workspace-name $(WORKSPACE_NAME) \
                --overwrite -v
          - task: AzureCLI@1
            displayName: 'Smoke test'
            inputs:
              azureSubscription: $(WORKSPACE_SVC_CONNECTION)
              scriptLocation: inlineScript
              workingDirectory: $(Build.SourcesDirectory)
              inlineScript: |
                set -e
                export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
                python -m ml_service.utils.smoke_test_scoring_service --service-type 'ACI' --service-name $(ACI_DEPLOYMENT_NAME) 
            
  