name: diabetes_regression_training_env
dependencies:
  # The python interpreter version.
  # Currently Azure ML Workbench only supports 3.5.2 and later.
  - python=3.7.*
  - pip

  - pip:
      # Base AzureML SDK
      - azureml-sdk

      # Must match AzureML SDK version.
      # https://docs.microsoft.com/en-us/azure/machine-learning/concept-environments
      - azureml-defaults

      # Training deps
      - scikit-learn

      # Scoring deps
      - inference-schema[numpy-support]

      # MLOps with R
      - azure-storage-blob